version: '3.4'

services:
  atherdev-nl:
    image: atherdev-nl
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3050:3050
